service: sls-node-api

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
  
provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs10.x
  memorySize: 128

package:
  exclude:
  - coverage/**
  - reports/**
  - .circleci/**
  - .git/**

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
          # authorizer: aws_iam    

resources:
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-offline